### ISSUE TITLE
QOnversion failures not throwing

### ISSUE THREAD

**Issue by rwrz** [qonversion/flutter-sdk#153] opened 2022-08-10 14:35 UTC
Recently, QOnversion started to fail A LOT. All API requests started to fail and when it happens, it doesn't throws anything on the Flutter side. Although I can see on the logs it returns 4xx or even 5xx errors.

Well, we need to be able to catch these errors, if not, lots of unexpected issues starts to happen. Like, subscriptions going to the wrong users and so on.

As you can see here, I tried to call a `QOnversion.identify()`, it didn't throw anything but on the logs below we can see that QOnversion is logging it and also Firebase Performance catched the http response.
```
D/Qonversion(20781): Thread - main identityRequest - failure - QonversionError: {code=BackendError, description=There was a backend error, additionalMessage=HTTP status code=403, error=failed to parse the backend response. }
I/FirebasePerformance(20781): Logging network request trace: https://api.qonversion.io/v2/identities (responseCode: 403, responseTime: 0,466ms)
```

Without throwing anything, a new user can sign-in on our App but it will remains the same for QOnversion, causing lots of conflicts when getting their subscriptions later on.

**Comment by suriksarkisyan** [comment] 2022-08-10 15:53
Hi, @rwrz .
Continuing our discussion from the support chat, I want to make some updates here. As I said, the problem is already solved. What about failed identity response and throwing an error? You are right; we are not throwing any error now because we are not sure it's useful for our users. Besides, when the identity request fails, and you ask for user permissions, we try to resend the identity request and get the most actual permissions. So you will get correct permissions (or error on permissions requests) even if the first identity request fails.

**Comment by rwrz** [comment] 2022-08-10 17:02
Permission request you mean here? `Qonversion.checkPermissions())`
It is not throwing errors to me. =/

**Comment by suriksarkisyan** [comment] 2022-08-10 17:24
> Permission request you mean here? `Qonversion.checkPermissions())`
> It is not throwing errors to me. =/

Yes, that one. That function should throw an error when it occurs, and if you added try and catch blocks. Our SDK is trying to get correct permissions (from cache or server) and return them. If it's not possible, the SDK will return an error.

**Comment by rwrz** [comment] 2022-08-10 17:46
Follow me on this:
- User A sign-in, we do a `QOnversion.identify()`, it works
- Then we retrieve his permissions with `Qonversion.checkPermissions()`, it works
- Now User A sign-out (logout)
- User B sign-in, and `QOnversion.identify()` **fails**

Should `Qonversion.checkPermissions()` throw an error or retrieve permissions from the cache with `User A` permissions?

Because, I'm almost sure that right now it just returns the wrong permissions and since it doesn't throw any exceptions, anywhere, I'm not able to identify that his permissions are wrong.

I was considering to use `.launch` instead. It throws errors, but seems wrong and I'm not sure how it will handle the user SignIn and SignOut.

**Comment by SpertsyanKM** [comment] 2022-08-16 15:07
Hello! Sorry for the late response. 

We have researched your case and found the issue. You are right - now, with the described scenario, there is an issue that the logged-out user will get cached permissions even if his own `identify` call fails. 

We have fixed this bug already and it will be released soon. 

Also, I want to let you know that we are now working on the new major versions of our SDKs, where all the network calls (and `identify` calls either) will obviously throw exceptions if something goes wrong. And all the SDKs logic will be more obvious and understandable.

**Comment by pixelfoxxx** [comment] 2022-08-25 09:27
Hello @rwrz! Thank you for waiting. 

We want to notify you that we've released the new version of SDK, where we've fixed the issue you're mentioning. 

Let us know if you have any further questions or if the issue persists. We'll be glad to assist!

**Closed by pixelfoxxx** 2022-08-25 09:27 UTC
Labels: in progress
